language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

after_success:
  - npm i -g coveralls
  - cat coverage/lcov.info | coveralls
  - npm run chore:deploy "npm run chore:release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
