name: Open Issue

on:
  issues:
    types:
      - "opened"
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          cd $GITHUB_WORKSPACE/.github/scripts/open-issue
          npm install --no-save
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/open-issue`);
            const result = await script({ github, context });

            if (result) {
              console.log(result);
            }
